spring.application.name=carmoloc-api

server.port=8080

# Datasource
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Security
jwt.secret=
jwt.expiration-ms=1200000
jwt.refresh-expiration-ms=604800000